"""
Wandroz — full-site deterministic QA gate

WHAT THIS ASKS
  "Is the generated website internally correct?"

  Its sibling, verify_reproducible.py, asks a different question — "can
  canonical source reproduce the intended site?" — and the two are kept
  apart deliberately. This one never looks at source coverage; it takes a
  built directory and audits it against the generator's own canonical
  constants.

WHY IT ASSERTS AGAINST build_site.py RATHER THAN ITS OWN COPY OF THE FACTS
  The class of bug this project keeps hitting is the same one every time:
  a fact (the city list, the evidence tier, the correction address) exists
  in two places and they drift. A QA script with its own hardcoded city
  list would be a third place. So the canonical values are imported from
  build_site and the script fails if they cannot be.

HARD FAILURES vs WARNINGS
  FAIL blocks deployment: broken links, missing pages, slug collisions,
  map/page mismatch, wrong canonical, malformed Booking URLs, stale
  navigation, methodology contradictions, a non-canonical contact address.
  WARN is reported and deployable: Booking destination ambiguity that
  needs a human eye, duplicate meta, cosmetic drift.

USAGE
    python3 pipeline/qa_full_site.py                      # audit dist/
    python3 pipeline/qa_full_site.py --dist build_candidate
    python3 pipeline/qa_full_site.py --report-dir qa_output
    python3 pipeline/qa_full_site.py --warnings-as-errors

EXIT CODES
    0  no hard failures
    1  at least one hard failure
    2  the audit itself could not run (bad path, unimportable generator)
"""

import argparse
import csv
import json
import os
import re
import sys
import urllib.parse
from collections import Counter, defaultdict

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(BASE_DIR)
sys.path.insert(0, BASE_DIR)

try:
    import build_site as BS
except Exception as exc:  # pragma: no cover - environment problem, not a site problem
    print("FATAL: cannot import pipeline/build_site.py (%s)." % exc)
    print("QA asserts against the generator's own constants and refuses to guess them.")
    sys.exit(2)


# --------------------------------------------------------------------------
# City registry
# --------------------------------------------------------------------------
# Maps the public URL slug to the data_zones key, the URL scheme, and where
# the zone data comes from. Three cities need it because the two names differ
# (monaco-di-baviera/munich) or the scheme does (torino, zurigo, milano are
# nested; every other illustrative city is flat).
#
# This belongs in build_site.py as the single canonical registry — see
# PATCH-build_site.md. Until it moves there, QA carries it and warns, rather
# than silently owning a second copy of the truth.
FALLBACK_REGISTRY = {
    #  url slug             data_zones key       scheme
    "amsterdam":            ("amsterdam",        "flat"),
    "athens":               ("athens",           "flat"),
    "barcelona":            ("barcelona",        "flat"),
    "berlin":               ("berlin",           "flat"),
    "brussels":             ("brussels",         "flat"),
    "budapest":             ("budapest",         "flat"),
    "dublin":               ("dublin",           "flat"),
    "edinburgh":            ("edinburgh",        "flat"),
    "firenze":              ("firenze",          "flat"),
    "krakow":               ("krakow",           "flat"),
    "lisbon":               ("lisbon",           "flat"),
    "madrid":               ("madrid",           "flat"),
    "milano":               ("milano",           "nested"),
    "monaco-di-baviera":    ("munich",           "flat"),
    "napoli":               ("napoli",           "flat"),
    "oslo":                 ("oslo",             "flat"),
    "paris":                ("paris",            "flat"),
    "praha":                ("praha",            "flat"),
    "roma":                 ("roma",             "flat"),
    "stockholm":            ("stockholm",        "flat"),
    "torino":               ("torino",           "nested"),
    "venezia":              ("venezia",          "flat"),
    "vienna":               ("vienna",           "flat"),
    "zurigo":               ("zurigo",           "nested"),
}
# London is generated by its own pipeline from data/scores/london.json and
# uses underscored borough slugs, so it is handled separately throughout.
LONDON_SLUG = "london"

VALID_TONES = {"green", "yellow", "red", "grey"}

# Copy that was true once and is not any more. Any of these in output is a
# hard failure — this is the check that would have caught the four stale
# production vintages while they were still candidates.
FORBIDDEN_PHRASES = [
    ("prototype build", "superseded footer wording; the canonical footer says 'in beta'"),
    ("not a finished product", "superseded footer wording"),
    ("both figures shown are the same", "stale: contradicts the single-badge rendering"),
    ("areas covered on Wandroz", "superseded cross-city comparability wording"),
    ("only automated", "stale methodology claim from the 3-city era"),
    ("Overall safety level", "superseded badge label"),
]

# Only ever legitimate for MANUAL_EXPERIMENTAL cities.
QUALITATIVE_PHRASES = ["qualitative first-pass", "general local knowledge", "public reputation"]

# Addresses retired from public use. This list does NOT define what is
# acceptable for the correction component — BS.CORRECTION_EMAIL alone does
# that. A retired address is a defect anywhere in public output, so this
# assertion is site-wide rather than scoped to the correction component.
LEGACY_EMAILS = {"dadenuoto@gmail.com"}

# Booking attribution parameters recognised by Booking.com / its affiliate
# networks. Presence is evidence of an attribution attempt; ABSENCE is
# conclusive, but presence alone never proves attribution actually works —
# see BOOKING_LAYERS below.
KNOWN_ATTRIBUTION_PARAMS = ("aid", "label", "sid", "utm_source", "utm_campaign")

# Booking correctness is four independent layers, and only the first two can
# be decided by reading HTML. Conflating them is how "the URL is valid" turns
# into "the link works", which is not the same claim.
#
#   A  URL_STRUCTURE_PASS            decidable here
#   B  WANDROZ_QUERY_MATCH           decidable here
#   C  BOOKING_DESTINATION_VERIFIED  needs a live Booking response — never
#                                    auto-passed by this script
#   D  AFFILIATE_ATTRIBUTION_VERIFIED needs the actual Booking/CJ account —
#                                    never auto-passed by this script
BOOKING_LAYERS = ("URL_STRUCTURE_PASS", "WANDROZ_QUERY_MATCH",
                  "BOOKING_DESTINATION_VERIFIED", "AFFILIATE_ATTRIBUTION_VERIFIED")

# Destination-mapping classes. Everything this script can see lands in
# UNVERIFIED at best; EXACT_AREA and TRAVELLER_ALIAS may only be set by a
# human or by a future live-checking layer, and are read from an optional
# reviewed ledger rather than inferred.
DEST_CLASSES = ("EXACT_AREA", "TRAVELLER_ALIAS", "CITY_FALLBACK", "UNVERIFIED", "FAIL")
DEST_LEDGER = os.path.join(BASE_DIR, "data_zones", "booking_destinations.json")

TAG_RE = re.compile(r"<[^>]+>")
HREF_RE = re.compile(r'href="([^"]+)"')
CANON_RE = re.compile(r'<link[^>]+rel="canonical"[^>]+href="([^"]+)"', re.I)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S | re.I)
BADGE_RE = re.compile(r'class="badge (green|yellow|red|grey)"')
ZONES_RE = re.compile(r"var ZONES\s*=\s*(\[.*?\]);\s*$", re.M | re.S)
TOGGLE_RE = re.compile(r"var SHOW_TOGGLE\s*=\s*(true|false)")
BOOKING_RE = re.compile(r'href="(https?://[^"]*booking\.com[^"]*)"')
# The correction component specifically: a mailto whose subject is a Wandroz
# correction. Both templates that emit it (borough.html:79,
# neighbourhood.html:93) build the subject as "Wandroz correction: <area>",
# so this matches the component rather than every address on the page.
CORRECTION_MAILTO_RE = re.compile(
    r'mailto:([\w.+-]+@[\w.-]+\.\w+)\?subject=Wandroz(?:%20|\+| )correction', re.I)


class Findings:
    def __init__(self):
        self.rows = []

    def add(self, severity, category, check, target, message):
        self.rows.append({
            "severity": severity, "category": category,
            "check": check, "target": target, "message": message,
        })

    def fail(self, *a):
        self.add("FAIL", *a)

    def warn(self, *a):
        self.add("WARN", *a)

    @property
    def failures(self):
        return [r for r in self.rows if r["severity"] == "FAIL"]

    @property
    def warnings(self):
        return [r for r in self.rows if r["severity"] == "WARN"]


def read(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        return f.read()


def load_zone_source(key):
    path = os.path.join(BASE_DIR, "data_zones", "%s.json" % key)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def registry(F):
    reg = getattr(BS, "CITY_REGISTRY", None)
    if reg:
        return {k: (v["data_key"], v["scheme"]) for k, v in reg.items()}
    F.warn("INVENTORY", "canonical-registry", "build_site.py",
           "no CITY_REGISTRY in build_site.py; QA is using its own fallback table. "
           "Move the registry into the generator so slug/scheme/data-key live in one place.")
    return dict(FALLBACK_REGISTRY)


def zone_page_path(dist, city, slug, scheme):
    if scheme == "nested":
        return os.path.join(dist, city, slug, "index.html")
    return os.path.join(dist, city, "%s.html" % slug)


def zone_page_url(city, slug, scheme):
    if scheme == "nested":
        return "/%s/%s/" % (city, slug)
    return "/%s/%s.html" % (city, slug)


# --------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------

def check_inventory(dist, reg, F):
    """Expected cities exist, and every source zone produced a page."""
    expected = {u.rstrip("/").rsplit("/", 1)[-1]
                for u in (c["url"] for c in BS.CITY_LINKS)}
    for slug in sorted(expected):
        hub = os.path.join(dist, slug, "index.html")
        if not os.path.isfile(hub):
            F.fail("INVENTORY", "city-hub-exists", slug,
                   "CITY_LINKS advertises /%s/ but %s does not exist" % (slug, hub))

    known = set(reg) | {LONDON_SLUG}
    for slug in sorted(expected - known):
        F.fail("INVENTORY", "city-registered", slug,
               "city is in CITY_LINKS but has no registry entry, so QA cannot audit its zones")
    for slug in sorted(known - expected):
        F.fail("INVENTORY", "city-registered", slug,
               "city is registered but absent from CITY_LINKS, so it is unreachable from the nav")

    counts = {}
    for city, (key, scheme) in sorted(reg.items()):
        src = load_zone_source(key)
        if src is None:
            F.fail("INVENTORY", "zone-source-exists", city,
                   "no pipeline/data_zones/%s.json — this city cannot be rebuilt from source" % key)
            continue
        zones = src.get("zones", [])
        counts[city] = len(zones)
        for z in zones:
            page = zone_page_path(dist, city, z["slug"], scheme)
            if not os.path.isfile(page):
                F.fail("INVENTORY", "zone-page-generated", "%s/%s" % (city, z["slug"]),
                       "zone is in source but no page was generated at %s"
                       % os.path.relpath(page, dist))

        generated = set()
        city_dir = os.path.join(dist, city)
        if os.path.isdir(city_dir):
            for entry in os.listdir(city_dir):
                full = os.path.join(city_dir, entry)
                if scheme == "flat" and entry.endswith(".html") and entry != "index.html":
                    generated.add(entry[:-5])
                elif scheme == "nested" and os.path.isdir(full):
                    generated.add(entry)
        for orphan in sorted(generated - {z["slug"] for z in zones}):
            F.fail("INVENTORY", "no-orphan-pages", "%s/%s" % (city, orphan),
                   "page exists in the build but has no zone in source")
    return counts


def check_slug_collisions(reg, F):
    for city, (key, _scheme) in sorted(reg.items()):
        src = load_zone_source(key)
        if not src:
            continue
        for slug, n in Counter(z["slug"] for z in src.get("zones", [])).items():
            if n > 1:
                F.fail("MAP", "slug-collision", "%s/%s" % (city, slug),
                       "%d zones share this slug; pages would overwrite each other" % n)
        for name, n in Counter(z["name"] for z in src.get("zones", [])).items():
            if n > 1:
                F.warn("MAP", "duplicate-zone-name", "%s/%s" % (city, name),
                       "%d zones share this display name" % n)


def check_map_integrity(dist, reg, F):
    """The hub's map polygons and the zone pages must describe one reality."""
    for city, (key, scheme) in sorted(reg.items()):
        hub = os.path.join(dist, city, "index.html")
        src = load_zone_source(key)
        if not os.path.isfile(hub) or not src:
            continue
        html = read(hub)
        m = ZONES_RE.search(html)
        if not m:
            F.fail("MAP", "hub-has-zones", city, "hub page has no `var ZONES` map data")
            continue
        try:
            map_zones = json.loads(m.group(1))
        except ValueError as exc:
            F.fail("MAP", "hub-zones-parse", city, "`var ZONES` is not valid JSON: %s" % exc)
            continue

        src_by_slug = {z["slug"]: z for z in src.get("zones", [])}
        map_by_slug = {z.get("slug"): z for z in map_zones}
        for slug in sorted(set(src_by_slug) - set(map_by_slug)):
            F.fail("MAP", "polygon-for-every-zone", "%s/%s" % (city, slug),
                   "zone has a page but no polygon on the city map")
        for slug in sorted(set(map_by_slug) - set(src_by_slug)):
            F.fail("MAP", "page-for-every-polygon", "%s/%s" % (city, slug),
                   "map shows a polygon with no corresponding zone in source")

        # Rating parity: the map and the detail page must agree.
        for slug, z in sorted(src_by_slug.items()):
            mz = map_by_slug.get(slug)
            if not mz:
                continue
            for field in ("day", "night"):
                if z.get(field) not in VALID_TONES:
                    F.fail("MAP", "valid-tone", "%s/%s" % (city, slug),
                           "%s=%r is not one of %s" % (field, z.get(field), sorted(VALID_TONES)))
                elif mz.get(field) != z.get(field):
                    F.fail("MAP", "rating-parity", "%s/%s" % (city, slug),
                           "map says %s=%s, source says %s=%s"
                           % (field, mz.get(field), field, z.get(field)))

        # Badge count is a CITY-level decision driven by SHOW_TOGGLE, never a
        # per-zone one. A city with any real day/night variation renders two
        # badges on EVERY zone page, uniform zones included.
        #
        # This distinction is not pedantic. Asserting the naive per-zone rule
        # (`day != night` → 2 badges) produces 55 false failures on Florence
        # alone — 55 uniform zones in a city whose SHOW_TOGGLE is true because
        # 19 other zones vary. Verified against the live site: Rome behaves
        # identically, Berlin (SHOW_TOGGLE=false) renders one badge everywhere.
        #
        # So the expected value is derived from the rendering rule the
        # generator actually uses, and the rule's own input is checked
        # separately below (SHOW_TOGGLE must agree with the source data).
        tm = TOGGLE_RE.search(html)
        if not tm:
            F.fail("MAP", "show-toggle-present", city, "hub page has no SHOW_TOGGLE flag")
            continue
        show_toggle = tm.group(1) == "true"
        expected_from_data = any(z["day"] != z["night"] for z in src.get("zones", []))
        if show_toggle != expected_from_data:
            F.fail("METHODOLOGY", "toggle-matches-data", city,
                   "SHOW_TOGGLE=%s but source data %s a real day/night split"
                   % (show_toggle, "has" if expected_from_data else "has no"))
        expected_badges = 2 if show_toggle else 1
        for slug in sorted(src_by_slug):
            page = zone_page_path(dist, city, slug, scheme)
            if not os.path.isfile(page):
                continue
            got = len(BADGE_RE.findall(read(page)))
            if got != expected_badges:
                F.fail("METHODOLOGY", "badge-count", "%s/%s" % (city, slug),
                       "expected %d badge(s) for SHOW_TOGGLE=%s, found %d"
                       % (expected_badges, show_toggle, got))


def check_navigation(dist, reg, F):
    """Every hub must offer the full canonical city list — no stale switchers."""
    expected = [(c["label"], c["url"].rstrip("/").rsplit("/", 1)[-1]) for c in BS.CITY_LINKS]
    for city in sorted(set(reg) | {LONDON_SLUG}):
        hub = os.path.join(dist, city, "index.html")
        if not os.path.isfile(hub):
            continue
        html = read(hub)
        missing = [label for label, slug in expected if "/%s/" % slug not in html]
        if missing:
            F.fail("NAVIGATION", "switcher-complete", city,
                   "city switcher is missing %d of %d cities: %s"
                   % (len(missing), len(expected), ", ".join(missing)))


def check_methodology(dist, reg, F):
    """Tier claims must match the tier, in both directions."""
    for city, (key, scheme) in sorted(reg.items()):
        meta = BS.CITY_METHODOLOGY.get(key) or BS.CITY_METHODOLOGY.get(city)
        if not meta:
            F.fail("METHODOLOGY", "tier-declared", city,
                   "no CITY_METHODOLOGY entry; FAQ, legend and homepage tag have nothing to derive from")
            continue
        tier = meta["tier"]
        src = load_zone_source(key)
        if not src:
            continue
        for z in src.get("zones", []):
            page = zone_page_path(dist, city, z["slug"], scheme)
            if not os.path.isfile(page):
                continue
            text = TAG_RE.sub(" ", read(page))
            target = "%s/%s" % (city, z["slug"])

            for phrase in QUALITATIVE_PHRASES:
                if phrase in text and tier != BS.MANUAL_EXPERIMENTAL:
                    F.fail("METHODOLOGY", "no-qualitative-claim-off-tier", target,
                           "%s tier page claims %r, which is only true for MANUAL_EXPERIMENTAL"
                           % (tier, phrase))
            if tier == BS.RESEARCH_BASED and re.search(
                    r"official (crime|police) statistics for this", text, re.I):
                F.fail("METHODOLOGY", "research-page-not-claiming-official", target,
                       "research-based page claims official crime statistics")
            if tier == BS.OFFICIAL_SNAPSHOT and "press research" in text.lower():
                F.fail("METHODOLOGY", "official-page-not-claiming-press", target,
                       "official-statistics page describes itself as press research")


def check_forbidden_copy(dist, F):
    for path, rel in walk_html(dist):
        text = TAG_RE.sub(" ", read(path))
        for phrase, why in FORBIDDEN_PHRASES:
            if phrase in text:
                F.fail("METHODOLOGY", "forbidden-copy", rel, "contains %r — %s" % (phrase, why))


def check_contact(dist, F):
    """Scoped to the correction-contact component, not to the whole page.

    Wandroz may legitimately grow other public addresses — support, privacy,
    partnerships — so "every address on the page must be the correction
    address" would be wrong the day one of those ships. The rule is narrower
    and survives that:

      1. the address in each *correction* mailto equals BS.CORRECTION_EMAIL.
         That constant remains the single source of truth for this function.
      2. no correction component carries an address we did not expect.
      3. separately and site-wide: a retired address must appear ZERO times
         anywhere in public output, in any context — not just in mailtos.
         This one is deliberately unscoped, because a leaked personal address
         is a defect wherever it appears.
    """
    canonical = BS.CORRECTION_EMAIL
    for path, rel in walk_html(dist):
        html = read(path)

        # (1) + (2) — the correction component only.
        for addr in sorted(set(CORRECTION_MAILTO_RE.findall(html))):
            if addr != canonical:
                F.fail("CONTACT", "correction-email-canonical", rel,
                       "correction link points at %r; BS.CORRECTION_EMAIL is %r"
                       % (addr, canonical))

        # (3) — retired addresses, anywhere on the page.
        for legacy in sorted(LEGACY_EMAILS):
            if legacy in html:
                F.fail("CONTACT", "no-legacy-email", rel,
                       "retired address %r appears in public output" % legacy)


def check_seo(dist, reg, F):
    titles = defaultdict(list)
    for path, rel in walk_html(dist):
        html = read(path)
        m = CANON_RE.search(html)
        expected = BS.SITE_URL + "/" + rel.replace(os.sep, "/").replace("index.html", "")
        expected = expected.rstrip("/") + ("/" if rel.endswith("index.html") else "")
        if not m:
            F.fail("SEO", "canonical-present", rel, "no rel=canonical link")
        elif m.group(1).rstrip("/") != expected.rstrip("/"):
            F.fail("SEO", "canonical-correct", rel,
                   "canonical is %r, expected %r" % (m.group(1), expected))
        t = TITLE_RE.search(html)
        if not t:
            F.fail("SEO", "title-present", rel, "no <title>")
        else:
            titles[t.group(1).strip()].append(rel)
    for title, pages in sorted(titles.items()):
        if len(pages) > 1:
            F.warn("SEO", "duplicate-title", pages[0],
                   "%d pages share the title %r" % (len(pages), title))

    sitemap = os.path.join(dist, "sitemap.xml")
    if not os.path.isfile(sitemap):
        F.fail("SEO", "sitemap-exists", "sitemap.xml", "no sitemap.xml in the build")
        return
    listed = {u.replace(BS.SITE_URL, "") or "/"
              for u in re.findall(r"<loc>([^<]+)</loc>", read(sitemap))}
    built = set()
    for _path, rel in walk_html(dist):
        url = "/" + rel.replace(os.sep, "/")
        built.add(url[:-len("index.html")] if url.endswith("index.html") else url)
    for url in sorted(built - listed):
        F.fail("SEO", "sitemap-complete", url, "page is built but missing from sitemap.xml")
    for url in sorted(listed - built):
        F.fail("SEO", "sitemap-no-phantoms", url, "sitemap lists a URL with no page behind it")


def check_links(dist, F):
    """Internal links must resolve to something the build actually produced."""
    for path, rel in walk_html(dist):
        base = os.path.dirname(path)
        for href in set(HREF_RE.findall(read(path))):
            if href.startswith(("http://", "https://", "mailto:", "#", "tel:", "data:")):
                continue
            clean = href.split("#", 1)[0].split("?", 1)[0]
            if not clean:
                continue
            if clean.startswith("/"):
                target = os.path.join(dist, clean.lstrip("/"))
            else:
                target = os.path.join(base, clean)
            if clean.endswith("/") or os.path.isdir(target):
                target = os.path.join(target, "index.html")
            if not os.path.exists(target):
                F.fail("LINKS", "internal-link-resolves", rel,
                       "link %r points at nothing (%s)" % (href, os.path.relpath(target, dist)))


def load_destination_ledger():
    """Human-reviewed destination verdicts, if any exist yet.

    Shape: {"<city>/<slug>": {"class": "EXACT_AREA", "checked": "2026-09-20",
                              "note": "Booking resolves this to the barrio"}}

    Nothing writes this file automatically. A class only appears here because
    a person opened the Booking search and looked, so the script can report
    verified coverage without ever inventing it.
    """
    if not os.path.isfile(DEST_LEDGER):
        return {}
    try:
        with open(DEST_LEDGER, encoding="utf-8") as f:
            return json.load(f)
    except ValueError:
        return {}


def check_booking(dist, reg, F, booking_rows):
    """Audit Booking CTAs across four independent layers.

    Layers A and B are decided here from the HTML. Layers C and D are NOT:
    a syntactically perfect URL whose `ss` matches our own source field still
    proves nothing about what Booking does with it, and the presence of an
    attribution parameter proves nothing about whether the account behind it
    is live. Both stay UNVERIFIED unless a reviewed ledger says otherwise.
    """
    ledger = load_destination_ledger()
    attribution_seen = Counter()
    checked_ctas = 0

    for city, (key, scheme) in sorted(reg.items()):
        src = load_zone_source(key)
        if not src:
            continue
        city_label = (src.get("label") or "").split(",")[0].strip()
        for z in src.get("zones", []):
            page = zone_page_path(dist, city, z["slug"], scheme)
            if not os.path.isfile(page):
                continue
            target = "%s/%s" % (city, z["slug"])
            urls = BOOKING_RE.findall(read(page))

            row = {
                "page": target,
                "url": urls[0] if urls else "",
                "ss": "",
                "source_query": z.get("query", ""),
                "URL_STRUCTURE_PASS": "FAIL",
                "WANDROZ_QUERY_MATCH": "FAIL",
                "BOOKING_DESTINATION_VERIFIED": "UNVERIFIED",
                "AFFILIATE_ATTRIBUTION_VERIFIED": "UNVERIFIED",
                "destination_class": "UNVERIFIED",
                "notes": "",
            }

            if not urls:
                row["notes"] = "no Booking CTA on the page"
                booking_rows.append(row)
                F.fail("BOOKING", "cta-present", target, "no Booking.com link on the zone page")
                continue
            if len(urls) > 1:
                F.warn("BOOKING", "single-cta", target, "%d Booking links on one page" % len(urls))

            url = urls[0]
            checked_ctas += 1
            parts = urllib.parse.urlsplit(url)
            qs = urllib.parse.parse_qs(parts.query)
            ss = (qs.get("ss") or [""])[0]
            row["ss"] = ss

            # ---- Layer A: URL structure -------------------------------------
            structural = []
            if parts.scheme != "https":
                structural.append("not https")
            if not parts.path.endswith("searchresults.html"):
                structural.append("unexpected path %r" % parts.path)
            if not ss:
                structural.append("no `ss` destination")
            if " " in parts.query:
                structural.append("unencoded space in query string")
            if structural:
                row["notes"] = "; ".join(structural)
                F.fail("BOOKING", "url-structure", target, "%s: %s" % ("; ".join(structural), url))
            else:
                row["URL_STRUCTURE_PASS"] = "PASS"

            # ---- Layer B: does the URL carry OUR query verbatim? -------------
            # This is an internal-consistency check between the generated page
            # and data_zones. It says nothing about Booking.
            if ss and ss == z.get("query"):
                row["WANDROZ_QUERY_MATCH"] = "PASS"
            elif ss:
                F.fail("BOOKING", "query-matches-source", target,
                       "Booking `ss`=%r but source query is %r" % (ss, z.get("query")))
                row["notes"] = (row["notes"] + "; " if row["notes"] else "") + "ss != source query"

            # ---- Layer C: destination — never auto-passed --------------------
            verdict = ledger.get(target, {})
            klass = verdict.get("class")
            if klass in DEST_CLASSES and klass not in ("UNVERIFIED",):
                row["destination_class"] = klass
                row["BOOKING_DESTINATION_VERIFIED"] = "PASS" if klass != "FAIL" else "FAIL"
                if klass == "FAIL":
                    F.fail("BOOKING", "destination-verified", target,
                           "reviewed and rejected: %s" % verdict.get("note", "no note"))
            else:
                row["BOOKING_DESTINATION_VERIFIED"] = "MANUAL_VERIFICATION_REQUIRED"
                if city_label and city_label.lower() not in (ss or "").lower():
                    F.warn("BOOKING", "destination-ambiguity", target,
                           "`ss`=%r does not name %s — a generic or duplicated place name can "
                           "resolve to another city or country" % (ss, city_label))

            # ---- Layer D: attribution — never auto-passed --------------------
            present = [p for p in KNOWN_ATTRIBUTION_PARAMS if p in qs]
            for p in present:
                attribution_seen[p] += 1
            row["AFFILIATE_ATTRIBUTION_VERIFIED"] = (
                "NOT_ATTRIBUTED_BY_CURRENT_CODE" if not present else "MANUAL_VERIFICATION_REQUIRED")
            if present:
                row["notes"] = (row["notes"] + "; " if row["notes"] else "") + \
                    "attribution params present: %s" % ",".join(present)

            booking_rows.append(row)

    # Duplicated destinations: distinct zones sending traffic to one search.
    by_ss = defaultdict(list)
    for row in booking_rows:
        if row["ss"]:
            by_ss[row["ss"]].append(row["page"])
    for ss, pages in sorted(by_ss.items()):
        if len(pages) > 1:
            for p in pages:
                for row in booking_rows:
                    if row["page"] == p and row["destination_class"] == "UNVERIFIED":
                        row["notes"] = (row["notes"] + "; " if row["notes"] else "") + \
                            "destination shared with %d other zone(s)" % (len(pages) - 1)
            F.warn("BOOKING", "shared-destination", pages[0],
                   "%d zones share destination %r: %s — check whether Booking can distinguish "
                   "them at all" % (len(pages), urllib.parse.unquote(ss), ", ".join(sorted(pages))))

    # Attribution is a site-wide fact, reported once.
    unattributed = sum(1 for r in booking_rows
                       if r["AFFILIATE_ATTRIBUTION_VERIFIED"] == "NOT_ATTRIBUTED_BY_CURRENT_CODE")
    if unattributed:
        F.warn("BOOKING", "affiliate-attribution", "site-wide",
               "%d of %d Booking CTAs carry no recognised attribution parameter (%s). "
               "Absence is conclusive; presence would still need account-side confirmation. "
               "Do not add parameters without the real account's authorised link format."
               % (unattributed, checked_ctas, ", ".join(KNOWN_ATTRIBUTION_PARAMS)))
    if attribution_seen:
        F.warn("BOOKING", "affiliate-attribution", "site-wide",
               "attribution parameters found in use: %s — layer D stays "
               "MANUAL_VERIFICATION_REQUIRED until confirmed against the account"
               % dict(attribution_seen))


def walk_html(dist):
    for root, _dirs, files in os.walk(dist):
        for name in sorted(files):
            if name.endswith(".html"):
                path = os.path.join(root, name)
                yield path, os.path.relpath(path, dist)


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def booking_layer_summary(booking_rows):
    """Roll the four layers up, keeping them strictly separate."""
    summary = {}
    for layer in BOOKING_LAYERS:
        summary[layer] = dict(Counter(r[layer] for r in booking_rows))
    summary["destination_class"] = dict(Counter(r["destination_class"] for r in booking_rows))
    summary["ctas_total"] = len(booking_rows)
    return summary


def write_reports(F, counts, dist, report_dir, booking_rows, reg):
    os.makedirs(report_dir, exist_ok=True)

    expected_cities = {u.rstrip("/").rsplit("/", 1)[-1] for u in (c["url"] for c in BS.CITY_LINKS)}
    built_cities = {slug for slug in expected_cities
                    if os.path.isfile(os.path.join(dist, slug, "index.html"))}
    nav_bad = sorted({r["target"] for r in F.rows if r["check"] == "switcher-complete"})

    payload = {
        "dist": os.path.abspath(dist),
        "pages_audited": sum(1 for _ in walk_html(dist)),
        "cities_expected": len(expected_cities),
        "cities_built": len(built_cities),
        "cities_missing": sorted(expected_cities - built_cities),
        "cities_audited": len(counts),
        "zone_counts": counts,
        "zones_in_source": sum(counts.values()),
        "florence": {
            "expected": 75,
            "generated": (1 if os.path.isfile(os.path.join(dist, "firenze", "index.html")) else 0)
                         + counts.get("firenze", 0),
        },
        "navigation": {
            "expected_cities_per_hub": len(BS.CITY_LINKS),
            "hubs_with_incomplete_switcher": nav_bad,
        },
        "booking": booking_layer_summary(booking_rows),
        "correction_email": {
            "canonical": BS.CORRECTION_EMAIL,
            "legacy_addresses_checked": sorted(LEGACY_EMAILS),
        },
        "totals": {"failures": len(F.failures), "warnings": len(F.warnings)},
        "findings": F.rows,
    }

    with open(os.path.join(report_dir, "booking_audit.csv"), "w", encoding="utf-8", newline="") as f:
        cols = ["page", "url", "ss", "source_query"] + list(BOOKING_LAYERS) + \
               ["destination_class", "notes"]
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        w.writerows(booking_rows)
    with open(os.path.join(report_dir, "qa_report.json"), "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")

    with open(os.path.join(report_dir, "qa_findings.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["severity", "category", "check", "target", "message"])
        w.writeheader()
        w.writerows(F.rows)

    with open(os.path.join(report_dir, "qa_inventory.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["city", "zones_in_source"])
        for city, n in sorted(counts.items()):
            w.writerow([city, n])
    return payload


def summarise(F, payload):
    print("=" * 72)
    print("WANDROZ FULL-SITE QA")
    print("=" * 72)
    print("pages audited        %d" % payload["pages_audited"])
    print("zones in source      %d" % payload["zones_in_source"])
    print("cities  expected %d / built %d%s"
          % (payload["cities_expected"], payload["cities_built"],
             "" if not payload["cities_missing"]
             else "   MISSING: " + ", ".join(payload["cities_missing"])))
    print("florence expected %d / generated %d"
          % (payload["florence"]["expected"], payload["florence"]["generated"]))
    nav = payload["navigation"]
    print("nav      expected %d cities per hub; hubs incomplete: %d%s"
          % (nav["expected_cities_per_hub"], len(nav["hubs_with_incomplete_switcher"]),
             "" if not nav["hubs_with_incomplete_switcher"]
             else "  (" + ", ".join(nav["hubs_with_incomplete_switcher"]) + ")"))
    print("email    canonical %s" % payload["correction_email"]["canonical"])
    print()
    print("BOOKING — four independent layers (C and D are never auto-passed)")
    for layer in BOOKING_LAYERS:
        states = payload["booking"][layer]
        print("  %-32s %s" % (layer, ", ".join("%s=%d" % kv for kv in sorted(states.items()))))
    print("  %-32s %s" % ("destination_class",
          ", ".join("%s=%d" % kv for kv in sorted(payload["booking"]["destination_class"].items()))))
    print()
    by_cat = Counter((r["severity"], r["category"]) for r in F.rows)
    if by_cat:
        print("%-10s %-14s %s" % ("SEVERITY", "CATEGORY", "COUNT"))
        for (sev, cat), n in sorted(by_cat.items()):
            print("%-10s %-14s %d" % (sev, cat, n))
        print()
    for row in F.failures[:60]:
        print("FAIL [%s/%s] %s — %s" % (row["category"], row["check"], row["target"], row["message"]))
    if len(F.failures) > 60:
        print("... and %d more failures (see qa_findings.csv)" % (len(F.failures) - 60))
    if F.failures and F.warnings:
        print()
    for row in F.warnings[:25]:
        print("WARN [%s/%s] %s — %s" % (row["category"], row["check"], row["target"], row["message"]))
    if len(F.warnings) > 25:
        print("... and %d more warnings (see qa_findings.csv)" % (len(F.warnings) - 25))
    print()
    print("RESULT: %d failure(s), %d warning(s)" % (len(F.failures), len(F.warnings)))


def main():
    ap = argparse.ArgumentParser(description="Wandroz full-site QA gate")
    ap.add_argument("--dist", default=os.path.join(REPO_DIR, "dist"),
                    help="directory to audit (default: dist/)")
    ap.add_argument("--report-dir", default=os.path.join(REPO_DIR, "qa_output"))
    ap.add_argument("--warnings-as-errors", action="store_true")
    args = ap.parse_args()

    dist = os.path.abspath(args.dist)
    if not os.path.isdir(dist):
        print("FATAL: %s is not a directory" % dist)
        return 2

    F = Findings()
    reg = registry(F)

    counts = check_inventory(dist, reg, F)
    check_slug_collisions(reg, F)
    check_map_integrity(dist, reg, F)
    check_navigation(dist, reg, F)
    check_methodology(dist, reg, F)
    check_forbidden_copy(dist, F)
    check_contact(dist, F)
    check_seo(dist, reg, F)
    check_links(dist, F)
    booking_rows = []
    check_booking(dist, reg, F, booking_rows)

    payload = write_reports(F, counts, dist, args.report_dir, booking_rows, reg)
    summarise(F, payload)
    print("reports written to %s" % os.path.relpath(args.report_dir, REPO_DIR))

    if F.failures:
        return 1
    if args.warnings_as_errors and F.warnings:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
